source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.3'
gem 'tzinfo'
gem 'tzinfo-data'
gem 'csv'
gem 'base64'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll-gist'
gem 'jekyll-feed'
gem 'jekyll-include-cache'
